fix(app): safely collect flows on the ui layer
it was the most likely cause of intermittent fatal crashes
on dismissing dialogs during flow collection. The crashes had
the following stracktrace:

IllegalStateException: Can not perform this action after onSaveInstanceState